# Generated by Django 4.1.5 on 2023-03-21 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('header1', models.TextField(blank=True, null=True)),
                ('header2', models.TextField(blank=True, null=True)),
                ('header3', models.TextField(blank=True, null=True)),
                ('header4', models.TextField(blank=True, null=True)),
                ('body1', models.TextField(blank=True, null=True)),
                ('body2', models.TextField(blank=True, null=True)),
                ('body3', models.TextField(blank=True, null=True)),
                ('body4', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.TextField()),
                ('region', models.TextField()),
                ('district', models.TextField()),
                ('village', models.TextField()),
                ('can_attend', models.TextField()),
                ('interested1', models.TextField()),
                ('why_you', models.TextField()),
                ('interested2', models.TextField()),
                ('expectations', models.TextField()),
                ('about_training', models.TextField()),
                ('trainings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainings', verbose_name='Тренинги')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/trainings/')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trainings.trainings')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('can_attend', models.BooleanField()),
                ('interested1', models.TextField()),
                ('why_you', models.TextField()),
                ('interested2', models.TextField()),
                ('expectations', models.TextField()),
                ('about_training', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoapi.district')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoapi.region')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainings', verbose_name='Тренинги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoapi.village')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('trainings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.trainings')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('replies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.comment')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.trainings')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
