# Generated by Django 4.1.5 on 2023-03-19 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/trainings/')),
                ('trainings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trainings.trainings')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('village', models.CharField(max_length=250)),
                ('goals', models.TextField()),
                ('expectations', models.TextField()),
                ('resume', models.CharField(max_length=250)),
                ('trainings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainings', verbose_name='Тренинги')),
            ],
        ),
    ]
