# Generated by Django 4.1.5 on 2023-03-20 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0002_trainingsimage_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingsApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email address')),
                ('goals', models.TextField()),
                ('expectations', models.TextField()),
                ('resume', models.FileField(upload_to='files/mentorship/')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoapi.district')),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainings', verbose_name='Тренинги')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoapi.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoapi.village')),
            ],
        ),
    ]
