# Generated by Django 4.1.5 on 2023-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trainings',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trainings',
            name='url',
        ),
        migrations.AddField(
            model_name='trainings',
            name='body1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainings',
            name='body2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainings',
            name='body3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainings',
            name='body4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainings',
            name='header1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainings',
            name='header2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainings',
            name='header3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainings',
            name='header4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
