# Generated by Django 4.1.5 on 2023-03-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_trainingsapplications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='TrainingsQuestions',
        ),
    ]
