# Generated by Django 4.1.5 on 2023-03-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_rename_goals_trainingsapplications_interested1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsapplications',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
