# Generated by Django 4.1.5 on 2023-03-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=250)),
                ('block1', models.TextField()),
                ('block2', models.TextField()),
                ('block3', models.TextField()),
                ('block4', models.TextField()),
                ('images1', models.ImageField(null=True, upload_to='images/landing_page/')),
                ('title2', models.CharField(max_length=250)),
                ('block5', models.TextField()),
                ('block6', models.TextField()),
                ('block7', models.TextField()),
                ('block8', models.TextField()),
                ('block9', models.TextField()),
                ('block10', models.TextField()),
                ('images2', models.ImageField(null=True, upload_to='images/landing_page/')),
                ('images3', models.ImageField(null=True, upload_to='images/landing_page/')),
                ('links', models.URLField()),
            ],
        ),
    ]
