# Generated by Django 4.1.7 on 2023-04-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0002_response_response_file_alter_question_question_type"),
        ("mentorship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="programs",
            field=models.ManyToManyField(blank=True, default=[], to="forms.event"),
        ),
    ]
