# Generated by Django 4.1.5 on 2023-03-20 07:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='MentorshipsApplications',
        ),
    ]
