# Generated by Django 4.1.5 on 2023-03-20 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorship', '0001_initial'),
        ('geoapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipapplications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipapplications',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoapi.village'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorship', verbose_name='отзыв о меноторской программе'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
