# Generated by Django 4.1.5 on 2023-03-20 08:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geoapi', '0001_initial'),
        ('mentorship', '0002_rename_applications_mentorshipsapplications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MentorshipsApplications',
            new_name='MentorshipApplications',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='MentorshipQuestions',
        ),
    ]
