# Generated by Django 4.1.7 on 2023-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="description",
            field=models.TextField(default="title"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.TextField(default="description"),
            preserve_default=False,
        ),
    ]
