# Generated by Django 4.1.7 on 2023-04-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="response_file",
            field=models.FileField(blank=True, null=True, upload_to="files/forms/"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("paragraph", "Paragraph"),
                    ("multiple_choice", "Multiple Choice"),
                    ("checkbox", "Checkbox"),
                    ("file", "File"),
                ],
                max_length=255,
            ),
        ),
    ]
