# Generated by Django 4.1.7 on 2023-04-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0002_response_response_file_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form",
                to="forms.event",
            ),
        ),
    ]
