# Generated by Django 4.1.7 on 2023-04-20 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0003_alter_form_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
