# Generated by Django 4.1.7 on 2023-04-19 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productcolor_productcolortranslation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Фото товара",
                "verbose_name_plural": "Фото товаров",
            },
        ),
    ]
