# Generated by Django 4.1.5 on 2023-03-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category_alter_productcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Имя категории'),
        ),
    ]
