# Generated by Django 4.1.5 on 2023-03-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='value',
            new_name='price',
        ),
    ]
