# Generated by Django 4.1.5 on 2023-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_status_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('product', 'last_updated'), 'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_date',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'В ожидании'), ('C', 'Подтвержден'), ('S', 'Отправлен'), ('D', 'Доставлен'), ('X', 'Отменен')], default='P', max_length=1, verbose_name='Статус'),
        ),
    ]
