# Generated by Django 4.1.5 on 2023-03-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
