# Generated by Django 4.1.5 on 2023-03-25 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0014_remove_order_stock_remove_order_total_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Feedback",
            new_name="Reply",
        ),
    ]
